version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp ./dist s3://angular-test123 --recursive
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
